project:
  type: website

website:
  title: "American Time Use Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: analysis.qmd
        text: Analysis
      - href: conclusions.qmd
        text: Conclusions
